### ISSUE TITLE
[FE-FEATURE] :  커뮤니티 페이지 구현

### ISSUE THREAD

**Issue by taejinii** [puppypawpaw/pawpaw-client#20]
## Description
작업 사항에 대해 설명해주세요.
커뮤니티 페이지를 구현합니다. 

참여중인 채팅방 과 추천하는 신규 채팅방은 캐러셀로 지금 뜨고있는 오픈채팅 방은 무한스크롤로 구현합니다.

## To-do
- [x] 참여중인 채팅방 캐러셀 구현
- [x] 신규 채팅방 캐러셀 구현
- [x] 지금 뜨고있는 채팅방 무한스크롤 구현

## ETC
추가내용이 있다면 적어주세요.
