### ISSUE TITLE
[FE-FEATURE] : 사이드바 구현 

### ISSUE THREAD

**Issue by JeonInguk** [puppypawpaw/pawpaw-client#3]
## Description
메인화면의 사이드바를 구현합니다.

## To-do
- [x] 데스크탑크기 레이아웃 작업
- [x] 토글 반응형 작업
- [x] 태블릿 반응형 작업
- [x] 모바일 반응형 작업
- [ ] 사이드바 애니메이션 작업
- [ ] useRouter.push VS [useRouter.prefetch & Link] prefetching 성능 비교
- [x] 라우팅 작업
