### ISSUE TITLE
[FE-FEATURE] :  채팅 관련 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by taejinii** [puppypawpaw/pawpaw-client#39]
## Description
작업 사항에 대해 설명해주세요.

채팅 관련 컴포넌트들을 리팩토링 합니다. 

## To-do
- [x] 쓰임에따른 폴더를 만들어 컴포넌트 분리
- [x] 추가된 기능,컴포넌트 개발
- [x] 재사용성 가능성이 높은 컴포넌트 리팩토링

## ETC
추가내용이 있다면 적어주세요.
