### ISSUE TITLE
[FE-FEATURE] :  실시간 채팅기능 구현

### ISSUE THREAD

**Issue by taejinii** [puppypawpaw/pawpaw-client#67]
## Description
작업 사항에 대해 설명해주세요.

실시간 채팅기능 및 부족했던 채팅룸 관련기능들을 추가할 예정입니다. 

## To-do
- [x] 실시간 채팅 기능 
- [x] 채팅룸 정보 조회
- [x] 이전 채팅 조회
- [x] 채팅룸 메타데이터 주입
- [x] 방장권한 위임
- [x] 채팅룸 삭제

## ETC
추가내용이 있다면 적어주세요.
